
apiVersion: v1
kind: Template

labels:
  application: ceph-s3-secret

metadata:
  name: ceph-s3-secret
  annotations:
    description: "Data Hub - Ceph Secret "
    tags: "mlflow,aicoe,datahub,mljob,storage,secret"

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_KEY}
  data:
  stringData:
    CEPH_KEY: "${CEPH_S3_ACCESS_KEY}"
    CEPH_SECRET: "${CEPH_S3_SECRET_KEY}"
    CEPH_HOST: "${CEPH_S3_ENDPOINT}"
    CEPH_BUCKET: "${CEPH_S3_BUCKET}"
    SECRET_KEY: "${SECRET_KEY}"


parameters:
- name: CEPH_S3_ACCESS_KEY
  required: true
- name: CEPH_S3_SECRET_KEY
  required: true
- name: CEPH_S3_ENDPOINT
  required: true
- name: CEPH_S3_BUCKET
  required: true
- name: SECRET_KEY
  required: true
